#release configuration
#Mon Sep 07 09:01:03 CEST 2026
completedPhase=check-poms
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.scm.com.github.stefanofornari\:nb-quick-question.empty=true
project.scm.com.github.stefanofornari\:quick-question-core.empty=true
project.scm.com.github.stefanofornari\:quick-question.connection=scm\:git\:https\://github.com/stefanofornari/quick-question.git
project.scm.com.github.stefanofornari\:quick-question.developerConnection=scm\:git\:https\://github.com/stefanofornari/quick-question.git
project.scm.com.github.stefanofornari\:quick-question.tag=HEAD
project.scm.com.github.stefanofornari\:quick-question.url=https\://github.com/stefanofornari/quick-question
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=@{project.version}
scm.url=scm\:git\:https\://github.com/stefanofornari/quick-question.git
